language: node_js
node_js: node
cache:
  directories:
    - node_modules
install:
  - yarn
before_script:
  - yarn global add parcel-bundler
script: yarn build
after_script:
  - cd public
  - git init
  - git config user.name "woaer"
  - git config user.email "zhangjingkang@qq.com"
  - git add .
  - git commit -m "update demo"
  - git push -f "${GH_TOKEN}@https://github.com/woaer/vue-bmob-wilddog-demo.git" master:gh-pages
  - echo -e "Done\n"